export const questions = [
    {
        _id: "1",
        title: "How to learn React?",
        description: "I want to learn React, can someone guide me?",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
        ],
        author: { _id: "1", name: "John Doe", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 10,
        answers: 5,
        views: 100,
        createdAt: new Date('2022-07-15'),
    },
    {
        _id: "2",
        title: "What is the best way to manage state in React?",
        description: "Should I use Redux, Context API, or something else?",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
        ],
        author: { _id: "2", name: "Jane Smith", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 15,
        answers: 8,
        views: 200,
        createdAt: new Date('2024-10-03'),
    },
    {
        _id: "3",
        title: "How to center a div in CSS?",
        description: "I'm struggling to center a div, any suggestions?",
        tags: [
            { _id: "2", name: "css" },
            { _id: "4", name: "html" },
            { _id: "5", name: "javascript" },
        ],
        author: { _id: "3", name: "Alice Johnson", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 7,
        answers: 3,
        views: 150,
        createdAt: new Date('2024-06-09'),
    },
    {
        _id: "4",
        title: "Why use TypeScript over JavaScript?",
        description: "What are the advantages of TypeScript?",
        tags: [
            { _id: "3", name: "typescript" },
            { _id: "1", name: "javascript" },
        ],
        author: { _id: "4", name: "Bob Brown", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 12,
        answers: 6,
        views: 180,
        createdAt: new Date('2022-03-30'),
    },
    {
        _id: "5",
        title: "How to optimize performance in Next.js?",
        description: "Looking for best practices to improve performance in Next.js applications.",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
            { _id: "6", name: "nextjs" },
        ],
        author: { _id: "5", name: "Charlie Lee", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 18,
        answers: 4,
        views: 220,
        createdAt: new Date('2023-02-14'),
    },
    {
        _id: "6",
        title: "What is the best way to structure a large React project?",
        description: "Looking for recommendations on folder structure and best practices.",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
        ],
        author: { _id: "6", name: "David Kim", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 9,
        answers: 2,
        views: 130,
        createdAt: new Date('2024-05-22'),
    },
    {
        _id: "7",
        title: "How to deploy a Next.js app?",
        description: "What are the steps to deploy a Next.js app to Vercel or other platforms?",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
            { _id: "6", name: "nextjs" },
        ],
        author: { _id: "7", name: "Eve Adams", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 14,
        answers: 5,
        views: 190,
        createdAt: new Date('2024-05-22'),
    },
    {
        _id: "8",
        title: "How to secure API requests in a frontend application?",
        description: "Looking for best practices to prevent unauthorized access.",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
            { _id: "7", name: "security" },
            { _id: "8", name: "api" },
        ],
        author: { _id: "8", name: "Frank White", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 16,
        answers: 7,
        views: 210,
        createdAt: new Date('2022-09-08'),
    },
    {
        _id: "9",
        title: "What is the difference between useEffect and useLayoutEffect?",
        description: "When should I use useLayoutEffect instead of useEffect?",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
        ],
        author: { _id: "9", name: "Grace Miller", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 11,
        answers: 3,
        views: 140,
        createdAt: new Date('2022-09-08'),
    },
    {
        _id: "10",
        title: "How to set up authentication in a Next.js app?",
        description: "Looking for methods to implement authentication in Next.js.",
        tags: [
            { _id: "1", name: "javascript" },
            { _id: "2", name: "react" },
        ],
        author: { _id: "10", name: "Henry Clark", image: "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" },
        upvotes: 20,
        answers: 9,
        views: 300,
        createdAt: new Date('2024-06-09'),
    },
];
